<span style="color: #60B5FC; font-weight: bold; font-size: 24px;">Homework 20230918</span>


<span style="color: navy; font-weight: bold; font-size: 20px;">Libraries:</span>


In [1]:
import numpy as np
import pandas as pd
import sklearn
import seaborn as sns

<span style="color: #AC1555; font-weight: bold; font-size: 18px;">Question 1:</span>

What's the version of Pandas that you installed?

In [144]:
print(pd.__version__)


2.1.0


The version of Pandas that I installed is 2.1.0

<span style="color: #AC1555; font-weight: bold; font-size: 18px;">Question 2:</span>

How many columns are in the dataset?

In [110]:
df = pd.read_csv('/Users/anagilabert/repos/machine-learning-zoomcamp/homework_ana/data/raw.githubusercontent.com_alexeygrigorev_datasets_master_housing.csv')

In [111]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [112]:
df.shape

(20640, 10)

There are 10 columns.

<span style="color: #AC1555; font-weight: bold; font-size: 18px;">Question 3:</span>

Select columns with missing data


In [113]:
null_mask = df.isnull() 


In [114]:
print(null_mask)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0          False     False               False        False           False   
1          False     False               False        False           False   
2          False     False               False        False           False   
3          False     False               False        False           False   
4          False     False               False        False           False   
...          ...       ...                 ...          ...             ...   
20635      False     False               False        False           False   
20636      False     False               False        False           False   
20637      False     False               False        False           False   
20638      False     False               False        False           False   
20639      False     False               False        False           False   

       population  households  median_income  media

In [115]:
columns_with_nulls = df.columns[null_mask.any()]

In [116]:
(print("columns_with_nulls:"))
print(columns_with_nulls)

columns_with_nulls:
Index(['total_bedrooms'], dtype='object')


<span style="color: #AC1555; font-weight: bold; font-size: 18px;">Question 4:</span>

How many unique values does the `ocean_proximity` column have?

In [117]:
unique_values = df['ocean_proximity'].nunique()

In [118]:
print(unique_values)

5


In [119]:
print(f'Ocean_proximity have {unique_values} unique values.')

Ocean_proximity have 5 unique values.


<span style="color: #AC1555; font-weight: bold; font-size: 18px;">Question 5:</span>

Average value of the 'median_house_value' for the houses near the bay

In [120]:
print(df[df['ocean_proximity'] == 'NEAR BAY'].head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY  


In [121]:
houses_near_bay = df[df['ocean_proximity'] == 'NEAR BAY']

In [122]:
mean_houses_near_bay = houses_near_bay['median_house_value'].mean()

In [123]:
print(f'The average value is: {mean_houses_near_bay}')

The average value is: 259212.31179039303


<span style="color: #AC1555; font-weight: bold; font-size: 18px;">Question 6:</span>

Has the mean value changed after filling missing values?

In [124]:
houses_near_bay_fill_null = houses_near_bay['median_house_value'].fillna(0)


In [125]:
mean_houses_near_bay_fill_null = houses_near_bay_fill_null.mean()

In [126]:
print('The mean of houses near bay fillin nulls with 0 is:')
print(mean_houses_near_bay_fill_null)

The mean of houses near bay fillin nulls with 0 is:
259212.31179039303


In [127]:
print(f'The mean value does not change filling nulls: mean({mean_houses_near_bay}) vs mean filling nulls({mean_houses_near_bay_fill_null})') 

The mean value does not change filling nulls: mean(259212.31179039303) vs mean filling nulls(259212.31179039303)


<span style="color: #AC1555; font-weight: bold; font-size: 18px;">Question 7:</span>

What's the value of the last element of `w`?

In [128]:
unique_values_info = df['ocean_proximity'].value_counts()
print(unique_values_info)

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64


1. Select all the options located on islands.

In [129]:
ocean_proximity_island = df[df['ocean_proximity'] == 'ISLAND']

In [130]:
print(ocean_proximity_island)

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318         

2. Select only columns `housing_median_age`, `total_rooms`, `total_bedrooms`.

In [131]:
selected_columns_island = ocean_proximity_island[['housing_median_age', 'total_rooms', 'total_bedrooms']]


3. Get the underlying NumPy array. Let's call it `X`.

In [132]:
X = selected_columns_island.values

In [133]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.

In [134]:
XTX = X.T @ X

In [135]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

5. Compute the inverse of `XTX`.

In [136]:
inverse_XTX = np.linalg.inv(XTX)

In [137]:
inverse_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

6. Create an array `y` with values `[950, 1300, 800, 1000, 1300]`.

In [138]:
y = np.array([950, 1300, 800, 1000, 1300])

In [139]:
y

array([ 950, 1300,  800, 1000, 1300])

7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.

In [140]:
mult_inverse_xtx_x = inverse_XTX @ X.T

In [141]:
w = mult_inverse_xtx_x @ y

In [142]:
w

array([23.12330961, -1.48124183,  5.69922946])

In [143]:
print(f'The las value of w is {w[-1]}')

The las value of w is 5.699229455065586
